config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    resource :session, only: %i[new create destroy]

    resources :users, only: %i[new create edit update]

    resources :questions do
      resources :answers, except: %i[new show]
    end

    namespace :admin do
      resources :users, only: %i[index create]
    end

    root 'pages#index'
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  belongs_to :user

  validates :title, presence: true, length: { minimum: 2 }
  validates :body, presence: true, length: { minimum: 2 }
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :set_question!, only: %i[show destroy edit update]

  def show
    @question = @question.decorate
    @answer = @question.answers.build
    @pagy, @answers = pagy @question.answers.order(created_at: :desc)
    @answers = @answers.decorate
  end

  def destroy
    @question.destroy
    flash[:success] = t('.success')
    redirect_to questions_path
  end

  def edit; end

  def update
    if @question.update question_params
      flash[:success] = t('.success')
      redirect_to questions_path
    else
      render :edit
    end
  end

  def index
    @pagy, @questions = pagy Question.order(created_at: :desc)
    @questions = @questions.decorate
  end

  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.build question_params
    if @question.save
      flash[:success] = t('.success')
      redirect_to questions_path
    else
      render :new
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def set_question!
    @question = Question.find params[:id]
  end
end

app/views/questions/_form.html.erb
<%= render 'shared/errors', object: @question %>

<%= form_with model: @question do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :title %>
    </div>

    <div class="col-sm-10">
      <%= f.text_field :title, placeholder: 'Title', class: 'form-control' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :body %>
    </div>

    <div class="col-sm-10">
      <%= f.text_area :body, class: 'form-control' %>
    </div>
  </div>

  <%= f.submit "Submit question!", class: 'btn btn-primary' %>
<% end %>

app/views/questions/_question.html.erb
<article class="card my-3">
  <section class="card-header">
    <%= question.user.gravatar %>
    <%= question.user.name_or_email %>
  </section>

  <div class="card-body">
    <h4><%= link_to question.title, question_path(question) %></h2>

    <section class="card-text">
      <time datetime="<%= question.formatted_created_at %>">
        <small><%= question.formatted_created_at %></small>
      </time>

      <p class="my-2">
        <%= truncate strip_tags(question.body), length: 150, omission: t('global.text.omission') %>
      </p>
    </section>

    <%= link_to t('global.button.show'), question_path(question), class: 'btn btn-primary' %> 
    <%= link_to t('global.button.edit'), edit_question_path(question), class: 'btn btn-secondary' %>
    <%= link_to t('global.button.delete'), question_path(question), class: 'btn btn-danger',
      data: {method: :delete, confirm: t('global.dialog.you_sure')} %>
  </div>
</article>

app/views/questions/edit.html.erb
<% provide :page_title, t('.title') %>
<% currently_at t('menu.questions') %>

<h1 class="mb-4"><%= t '.title' %></h1>

<%= render 'form' %>

app/views/questions/index.html.erb
<% provide :page_title, t('.title') %>
<% currently_at t('menu.questions') %>

<h1 class="mb-4"><%= t('.title') %></h1>

<%= link_to t('.new'), new_question_path, class: 'btn btn-primary btn-lg mb-3' %>
<%= pagination @pagy %>
<%= render @questions %>
<%= pagination @pagy %>

app/views/questions/new.html.erb
<% provide :page_title, t('.title') %>
<% currently_at t('menu.questions') %>

<h1 class="mb-4"><%= t('.title') %></h1>

<%= render 'form' %>

app/views/questions/show.html.erb
<% provide :page_title, @question.title %>
<% currently_at t('menu.questions') %>

<h1 class="mb-4"><%= @question.title %></h1>

<time datetime="<%= @question.formatted_created_at %>">
  <%= @question.formatted_created_at %>
</time>

<div class="lead my-3">
  <%= sanitize @question.body %>
</div>

<div class="mb-3">
  <%= @question.user.gravatar %>
  <%= @question.user.name_or_email %>
</div>

<div class="border-top border-bottom py-3">
  <div class="btn-group">
    <%= link_to t('global.button.show'), question_path(@question), class: 'btn btn-primary' %> 
    <%= link_to t('global.button.edit'), edit_question_path(@question), class: 'btn btn-secondary' %>
    <%= link_to t('global.button.delete'), question_path(@question), class: 'btn btn-danger',
      data: {method: :delete, confirm: t('global.dialog.you_sure')} %>
  </div>
</div>

<h2 class="my-3"><%= t '.write_answer' %></h2>

<%= render 'answers/form' %>

<h2 class="mt-5 mb-3"><%= t '.answers' %></h2>

<%= pagination @pagy %>
<%= render partial: 'answers/answer', collection: @answers,
  as: :answer, locals: {question: @question} %>
<%= pagination @pagy %>