config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    resource :session, only: %i[new create destroy]

    resources :users, only: %i[new create edit update]

    resources :questions do
      resources :answers, except: %i[new show]
    end

    namespace :admin do
      resources :users, only: %i[index create]
    end

    root 'pages#index'
  end
end

app/views/shared/_errors.html.erb
<% if object.errors.full_messages.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_menu.html.erb
<%= provide :main_menu do %>
  <header class="p-3 bg-dark text-white">
    <div class="container">
      <nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><%= nav_tab t('menu.home'), root_path,
            class: 'nav-link px-2', current_page: current_page %></li>
          <li><%= nav_tab t('menu.questions'), questions_path,
            class: 'nav-link px-2', current_page: current_page %></li>
        </ul>

        <ul class="nav col-12 col-lg-auto mb-2 mb-md-0">
          <li class="dropdown">
            <%= link_to '#', class: 'nav-link px-2 dropdown-toggle text-white',
              data: {"bs-toggle": 'dropdown'} do %>
              <%= tag.div '', class: "flag #{I18n.locale}-flag mt-1" %>
              <%= t I18n.locale %>
            <% end %>
            
            <ul class="dropdown-menu">
              <% I18n.available_locales.each do |locale| %>
                <li>
                  <% if I18n.locale == locale %>
                    <%= tag.span t(locale), class: 'dropdown-item' %>
                  <% else %>
                    <%= link_to t(locale), root_path(locale: locale),
                      class: 'dropdown-item' %>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </li>
        </ul>

        <ul class="nav col-12 col-lg-auto mb-2 mb-md-0">
          <% if user_signed_in? %>
            <li class="dropdown">
              <%= link_to '#',
                class: 'nav-link px-2 dropdown-toggle text-white',
                data: {"bs-toggle": 'dropdown'} do %>
                <%= current_user.gravatar %>
                <%= current_user.name_or_email %>
              <% end %>
              
              <ul class="dropdown-menu">
                <li>
                  <%= link_to t('menu.edit_profile'), edit_user_path(current_user),
                    class: 'dropdown-item' %>
                </li>

                <li><hr class="dropdown-divider"></li>

                <li>
                  <%= link_to t('menu.log_out'), session_path,
                    class: 'dropdown-item', data: {method: :delete} %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= nav_tab t('menu.sign_up'), new_user_path,
              class: 'nav-link px-2', current_page: current_page %></li>

            <li><%= nav_tab t('menu.log_in'), new_session_path,
              class: 'nav-link px-2', current_page: current_page %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>
<% end %>