config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    resource :session, only: %i[new create destroy]

    resources :users, only: %i[new create edit update]

    resources :questions do
      resources :answers, except: %i[new show]
    end

    namespace :admin do
      resources :users, only: %i[index create]
    end

    root 'pages#index'
  end
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user

  validates :body, presence: true, length: { minimum: 5 }
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  include ActionView::RecordIdentifier

  before_action :set_question!
  before_action :set_answer!, except: :create

  def update
    if @answer.update answer_update_params
      flash[:success] = t '.success'
      redirect_to question_path(@question, anchor: dom_id(@answer))
    else
      render :edit
    end
  end

  def edit
  end

  def create
    @answer = @question.answers.build answer_create_params

    if @answer.save
      flash[:success] = t '.success'
      redirect_to question_path(@question)
    else
      @question = @question.decorate
      @pagy, @answers = pagy @question.answers.order created_at: :desc
      @answers = @answers.decorate
      render 'questions/show'
    end
  end

  def destroy
    @answer.destroy
    flash[:success] = t '.success'
    redirect_to question_path(@question)
  end

  private

  def answer_create_params
    params.require(:answer).permit(:body).merge(user: current_user)
  end

  def answer_update_params
    params.require(:answer).permit(:body)
  end

  def set_question!
    @question = Question.find params[:question_id]
  end

  def set_answer!
    @answer = @question.answers.find params[:id]
  end
end

app/views/answers/_answer.html.erb
<%= tag.article class: 'mb-3 card border-0', id: dom_id(answer) do %>
  <div class="row g-0">
    <div class="col-sm-auto text-sm-center align-self-center">
      <%= answer.user.gravatar size: 50, css_class: 'd-block' %>
      <%= answer.user.name_or_email %>
    </div>
    <div class="col-sm">
      <div class="card-body">
        <section class="card-text mb-3">
          <div class="col-sm-9">
            <small><time datetime="<%= answer.formatted_created_at %>">
              <%= answer.formatted_created_at %>
            </time></small>

            <div class="mt-2">
              <%= sanitize answer.body %>
            </div>
          </div>
        </section>

        <%= link_to t('global.button.edit'), edit_question_answer_path(question, answer), 
          class: 'btn btn-info btn-sm' %>
        <%= link_to t('global.button.delete'), question_answer_path(question, answer), class: 'btn btn-danger btn-sm',
          data: {method: :delete, confirm: t('global.dialog.you_sure')} %>
      </div>
    </div>
  </div>
<% end %>

app/views/answers/_form.html.erb
<%= render 'shared/errors', object: @answer %>

<%= form_with model: [@question, @answer] do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :body %>
    </div>

    <div class="col-sm-10">
      <%= f.text_area :body, class: 'form-control' %>
    </div>
  </div>

  <%= f.submit "Submit answer!", class: 'btn btn-primary' %>
<% end %>

app/views/answers/edit.html.erb
<% provide :page_title, t('.title') %>
<% currently_at t('menu.questions') %>

<h1><%= t '.title' %></h1>

<%= render 'form' %>