config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    resource :session, only: %i[new create destroy]

    resources :users, only: %i[new create edit update]

    resources :questions do
      resources :answers, except: %i[new show]
    end

    namespace :admin do
      resources :users, only: %i[index create]
    end

    root 'pages#index'
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  attr_accessor :old_password, :remember_token

  has_secure_password validations: false

  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy

  validate :password_presence
  validate :correct_old_password, on: :update, if: -> { password.present? }
  validates :password, confirmation: true, allow_blank: true,
                      length: { minimum: 8, maximum: 70 }

  validates :email, presence: true, uniqueness: true, 'valid_email_2/email': true
  validate :password_complexity

  before_save :set_gravatar_hash, if: :email_changed?

  def remember_me
    self.remember_token = SecureRandom.urlsafe_base64
    # rubocop:disable Rails/SkipsModelValidations
    update_column :remember_token_digest, digest(remember_token)
    # rubocop:enable Rails/SkipsModelValidations
  end

  def forget_me
    # rubocop:disable Rails/SkipsModelValidations
    update_column :remember_token_digest, nil
    # rubocop:enable Rails/SkipsModelValidations
    self.remember_token = nil
  end

  def remember_token_authenticated?(remember_token)
    return false if remember_token_digest.blank?

    BCrypt::Password.new(remember_token_digest).is_password?(remember_token)
  end

  private

  def set_gravatar_hash
    return if email.blank?

    hash = Digest::MD5.hexdigest email.strip.downcase
    self.gravatar_hash = hash
  end

  def digest(string)
    cost = if ActiveModel::SecurePassword
              .min_cost
            BCrypt::Engine::MIN_COST
          else
            Crypt::Engine.cost
          end
    BCrypt::Password.create(string, cost: cost)
  end

  def correct_old_password
    return if BCrypt::Password.new(password_digest_was).is_password?(old_password)

    errors.add :old_password, 'is incorrect'
  end

  def password_complexity
    # Regexp extracted from https://stackoverflow.com/questions/19605150/regex-for-password-must-contain-at-least-eight-characters-at-least-one-number-a
    return if password.blank? || password =~ /(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-])/

    msg = 'complexity requirement not met. Length should be 8-70 characters and ' \
          'include: 1 uppercase, 1 lowercase, 1 digit and 1 special character'
    errors.add :password, msg
  end

  def password_presence
    errors.add(:password, :blank) if password_digest.blank?
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :require_no_authentication, only: %i[new create]
  before_action :require_authentication, only: %i[edit update]
  before_action :set_user!, only: %i[edit update]

  def edit; end

  def update
    if @user.update user_params
      flash[:success] = t '.success'
      redirect_to edit_user_path(@user)
    else
      render :edit
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      sign_in @user
      flash[:success] = t('.success', name: current_user.name_or_email)
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def set_user!
    @user = User.find params[:id]
  end

  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation, :old_password)
  end
end

app/views/admin/users/_user.html.erb
<tr>
  <th scope="row"><%= user.id %></th>
  <td><%= user.name %></td>
  <td><%= user.email %></td>
  <td><%= user.created_at %></td>
  <td><%= user.updated_at %></td>
</tr>

app/views/admin/users/index.html.erb
<% provide :page_title, t('.title') %>
<% currently_at t('menu.users') %>

<h1 class="mb-4"><%= t '.title' %></h1>

<div class="btn-group mb-3">
  <%= link_to t('.download_zipped'), admin_users_path(format: :zip),
    class: 'btn btn-secondary' %>
</div>

<%= pagination @pagy %>
<% scope = 'activerecord.attributes.user' %>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col"><%= t 'name', scope: scope %></th>
      <th scope="col"><%= t 'email', scope: scope %></th>
      <th scope="col"><%= t 'created_at', scope: scope %></th>
      <th scope="col"><%= t 'updated_at', scope: scope %></th>
    </tr>
  </thead>
  <tbody>
    <%= render @users %>
  </tbody>
</table>

<%= pagination @pagy %>

<h2 class="mb-3"><%= t '.upload_zipped' %></h2>

<%= form_with url: admin_users_path do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :archive, t('.upload_form.archive') %>
    </div>

    <div class="col-sm-10">
      <%= f.file_field :archive, class: 'form-control' %>
    </div>
  </div>

  <%= f.submit t('.upload_form.submit'), class: 'btn btn-primary' %>
<% end %>